language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy
  - pypy3
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - coverage run --branch -m unittest discover -v
after_success:
  - codecov
notifications:
  email:
    - dickinsm@gmail.com
